export const SHOW_ALL_TEACHER = 'SHOW_ALL_TEACHER'
export const SHOW_TRANSCRIPT = 'SHOW_TRANSCRIPT'
export const SHOW_SETTINGS = 'SHOW_SETTINGS'
export const SHOW_REQUESTS = 'SHOW_REQUESTS'
export const SHOW_STUDENT = 'SHOW_STUDENT'
export const SHOW_ADMIN = 'SHOW_ADMIN'
export const SHOW_EVENTS = 'SHOW_EVENTS'

export const CHANGE_SEMISTER_REQUEST = 'CHANGE_SEMISTER_REQUEST'
export const CHANGE_SEMISTER_SUCCESS = 'CHANGE_SEMISTER_SUCCESS'
export const CHANGE_SEMISTER_ERROR = 'CHANGE_SEMISTER_ERROR'

export const GET_REQUESTS_REQUEST = 'GET_REQUESTS_REQUEST'
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS'
export const GET_REQUESTS_ERROR = 'GET_REQUESTS_ERROR'

export const REQUEST_APPROVE_REQUEST = 'REQUEST_APPROVE_REQUEST'
export const REQUEST_APPROVE_SUCCESS = 'REQUEST_APPROVE_SUCCESS'
export const REQUEST_APPROVE_FAIL = 'REQUEST_APPROVE_FAIL'

export const NEW_REQUESTS_COUNT_REQUEST = 'NEW_REQUESTS_COUNT_REQUEST'
export const NEW_REQUESTS_COUNT_SUCCESS = 'NEW_REQUESTS_COUNT_SUCCESS'
export const NEW_REQUESTS_COUNT_FAIL = 'NEW_REQUESTS_COUNT_FAIL'

export const DELETE_REQUEST_REQUEST = 'DELETE_REQUEST_REQUEST'
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS'
export const DELETE_REQUEST_FAIL = 'DELETE_REQUEST_FAIL'

export const DELETE_TEACHER_REQUEST = 'DELETE_TEACHER_REQUEST'
export const DELETE_TEACHER_SUCCESS = 'DELETE_TEACHER_SUCCESS'
export const DELETE_TEACHER_FAIL = 'DELETE_TEACHER_FAIL'

export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST'
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL'

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL'

export const ADMIN_PROFILE_REQUEST = 'ADMIN_PROFILE_REQUEST'
export const ADMIN_PROFILE_SUCCESS = 'ADMIN_PROFILE_SUCCESS'
export const ADMIN_PROFILE_FAIL = 'ADMIN_PROFILE_FAIL'

export const UPDATE_ADMIN_REQUEST = 'UDPDATE_ADMIN_REQUEST'
export const UPDATE_ADMIN_SUCCESS = 'UDPDATE_ADMIN_SUCCESS'
export const UPDATE_ADMIN_FAIL = 'UDPDATE_ADMIN_FAIL'

export const RESET_ASSIGNED_REQUEST = 'RESET_ASSIGNED_REQUEST'
export const RESET_ASSIGNED_SUCCESS = 'RESET_ASSIGNED_SUCCESS'
export const RESET_ASSIGNED_FAIL = 'RESET_ASSIGNED_FAIL'

export const ASSIGN_HOMEROOM_REQUEST = 'ASSIGN_HOMEROOM_REQUEST'
export const ASSIGN_HOMEROOM_SUCCESS = 'ASSIGN_HOMEROOM_SUCCESS'
export const ASSIGN_HOMEROOM_FAIL = 'ASSIGN_HOMEROOM_FAIL'

export const TEACHER_DETAIL_REQUEST = 'TEACHER_DETAIL_REQUEST'
export const TEACHER_DETAIL_SUCCESS = 'TEACHER_DETAIL_SUCCESS'
export const TEACHER_DETAIL_FAIL = 'TEACHER_DETAIL_FAIL'

export const REMOVE_ASSIGN_REQUEST = 'REMOVE_ASSIGN_REQUEST'
export const REMOVE_ASSIGN_SUCCESS = 'REMOVE_ASSIGN_SUCCESS'
export const REMOVE_ASSIGN_FAIL = 'REMOVE_ASSIGN_FAIL'

export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST'
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS'
export const ADD_EVENT_FAIL = 'ADD_EVENT_FAIL'

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST'
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS'
export const GET_EVENT_FAIL = 'GET_EVENT_FAIL'

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL'

export const EDIT_EVENT_REQUEST = 'EDIT_EVENT_REQUEST'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'
export const EDIT_EVENT_FAIL = 'EDIT_EVENT_FAIL'

export const UPDATE_TEACHER_REQUEST = 'UPDATE_TEACHER_REQUEST'
export const UPDATE_TEACHER_SUCCESS = 'UPDATE_TEACHER_SUCCESS'
export const UPDATE_TEACHER_FAIL = 'UPDATE_TEACHER_FAIL'