export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST"
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS"
export const REGISTER_STUDENT_FAIL = "REGISTER_STUDENT_FAIL"

export const GET_STUDENT_DETAIL_REQUEST = "GET_STUDENT_DETAIL_REQUEST"
export const GET_STUDENT_DETAIL_SUCCESS = "GET_STUDENTS_DETAIL_SUCCESS"
export const GET_STUDENT_DETAIL_FAIL = "GET_STUDENT_DETAIL_FAIL"

export const GET_TRANSCRIPT_REQUEST = "GET_TRANSCRIPT_REQUEST"
export const GET_TRANSCRIPT_SUCCESS = "GET_TRANSCRIPT_SUCCESS"
export const GET_TRANSCRIPT_FAIL = "GET_TRANSCRIPT_FAIL"

export const GET_SCORE_REQUEST = "GET_SCORE_REQUEST"
export const GET_SCORE_SUCCESS = "GET_SCORE_SUCCESS"
export const GET_SCORE_FAIL = "GET_SCORE_FAIL"

export const ADD_REQUEST_REQUEST = "ADD_REQUEST_REQUEST"
export const ADD_REQUEST_SUCCESS = "ADD_REQUEST_SUCCESS"
export const ADD_REQUEST_FAIL = "ADD_REQUEST_FAIL"

export const SHOW_MARK = "SHOW_MARK"
export const SHOW_PROFILE = "SHOW_PROFILE"

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL"