export const REGISTER_TEACHER_REQUEST = "REGISTER_TEACHER_REQUEST"
export const REGISTER_TEACHER_SUCCESS = "REGISTER_TEACHER_SUCCESS"
export const REGISTER_TEACHER_FAIL = "REGISTER_TEACHER_FAIL"

export const GET_TEACHERS_REQUEST = "GET_TEACHERS_REQUEST"
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS"
export const GET_TEACHERS_FAIL = "GET_TEACHERS_FAIL"

export const GET_TEACHER_DETAIL_REQUEST = "GET_TEACHER_DETAIL_REQUEST"
export const GET_TEACHER_DETAIL_SUCCESS = "GET_TEACHERS_DETAIL_SUCCESS"
export const GET_TEACHER_DETAIL_FAIL = "GET_TEACHER_DETAIL_FAIL"

export const ASSIGN_TEACHER_REQUEST = "ASSIGN_TEACHER_REQUEST"
export const ASSIGN_TEACHER_SUCCESS = "ASSIGN_TEACHER_SUCCESS"
export const ASSIGN_TEACHER_FAIL = "ASSIGN_TEACHER_FAIL"

export const GET_MYSTUDENTS_REQUEST = "GET_MYSTUDENTS_REQUEST"
export const GET_MYSTUDENTS_SUCCESS = "GET_MYSTUDENTS_SUCCESS"
export const GET_MYSTUDENTS_FAIL = "GET_MYSTUDENTS_FAIL"

export const VIEW_ATTENDANCE_REQUEST = "VIEW_ATTENDANCE_REQUEST"
export const VIEW_ATTENDANCE_SUCCESS = "VIEW_ATTENDANCE_SUCCESS"
export const VIEW_ATTENDANCE_FAIL = "GET_MYSTUDENTS_FAIL"

export const GET_ATTENDANCE_REQUEST = 'GET_ATTENDANCE_REQUEST'
export const GET_ATTENDANCE_SUCCESS = 'GET_ATTENDANCE_SUCCESS'
export const GET_ATTENDANCE_FAIL = 'GET_ATTENDANCE_FAIL'

export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST'
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL'

export const SHOW_ATTENDANCE = 'SHOW_ATTENDANCE'
export const SHOW_STUDENTS = 'SHOW_STUDENTS'
export const SHOW_RANK = 'SHOW_RANK'

export const SET_STUDENT_MARK_REQUEST = "SET_STUDENT_MARK_REQUEST"
export const SET_STUDENT_MARK_SUCCESS = "SET_STUDENT_MARK_SUCCESS"
export const SET_STUDENT_MARK_FAIL = "SET_STUDENT_MARK_FAIL"

export const SET_ATTENDANCE_DATE_REQUEST = "SET_ATTENDANCE_DATE_REQUEST"
export const SET_ATTENDANCE_DATE_SUCCESS = "SET_ATTENDANCE_DATE_SUCCESS"
export const SET_ATTENDANCE_DATE_FAIL = "SET_ATTENDANCE_DATE_FAIL"

export const SET_STUDENT_ATTENDANCE_REQUEST = "SET_STUDENT_ATTENDANCE_REQUEST"
export const SET_STUDENT_ATTENDANCE_SUCCESS = "SET_STUDENT_ATTENDANCE_SUCCESS"
export const SET_STUDENT_ATTENDANCE_FAIL = "SET_STUDENT_ATTENDANCE_FAIL"

export const SET_STUDENT_RANK_REQUEST = "SET_STUDENT_RANK_REQUEST"
export const SET_STUDENT_RANK_SUCCESS = "SET_STUDENT_RANK_SUCCESS"
export const SET_STUDENT_RANK_FAIL = "SET_STUDENT_RANK_FAIL"

export const SET_SUBJECT = "SET_SUBJECT"

export const GET_ATTENDANCE_REPORT_REQUEST = 'GET_ATTENDANCE_REPORT_REQUEST'
export const GET_ATTENDANCE_REPORT_SUCCESS = 'GET_ATTENDANCE_REPORT_SUCCESS'
export const GET_ATTENDANCE_REPORT_FAIL = 'GET_ATTENDANCE_REPORT_FAIL'