export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"


export const GET_SEMISTER_REQUEST = "GET_SEMISTER_REQUEST"
export const GET_SEMISTER_SUCCESS = "GET_SEMISTER_SUCCESS"
export const GET_SEMISTER_FAIL = "GET_SEMISTER_FAIL"